version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./src:/src

volumes:
  postgres_data:
